### ISSUE TITLE
The web server is about to be messed with

### ISSUE THREAD

**Issue by Olical** [trillek-team/trillek-team.github.io#1]
My current web host, webfaction, sent me an email the other day regarding a migration they're performing at "Friday, 17 March 2017 between 19:00 to 21:00 UTC".

They're moving my server to another server, somehow, which will require work from me to sync up all DNS record and migrate everything / make sure it even works. This probably means that stuff like the logger and maybe the WordPress instance will die. I'm also not sure if I have total control of the required domains.

So, I was planning on finally migrating all my stuff to a new host, I was wondering if anyone would like to take up the mantle of hosting all trillek services or if we should continue to host it at all?

I don't really have the time to migrate everything right now and I'll be on holiday all next week, so I don't think I'll be able to guarantee that I can keep everything running over this server change. I can probably dump all the databases and the code somewhere if someone would like it to pick up the hosting.

I don't own the trillek domain though, I just have some sort of DNS control, but the domain could expire soon for all I know. I'm just interested in keeping my personal site running right now without paying ~$130 a year.

I want to use digitalocean or something ideally, but I'd pay per service, not per server. It'd cost me even more to keep running trillek.

So, not sure what to do, thought I'd mention you guys, but not sure who else would be interested.

Thanks,

Ollie / Olical / Wolfy :smile:

**Comment by milesrout** [comment]
ACK. I'll have to look at this when I get home from work. Thanks for
letting us know

**Comment by milesrout** [comment]
Sorry now I'm at work I'll elaborate slightly.

We have a wiki, forums, IRC logging, and that's it, is that right? We aren't hosting the actual trillek.org homepage on your servers anymore (hence the .github.io repo). I'm not sure the forums hold much of value, the IRC logs definitely *do* hold value, and the wiki IMO holds value. I'm happy to chuck them all on a $5/month DigitalOcean instance and pay for & maintain it.

**Comment by milesrout** [comment]
I'm home at the moment, sorry about the delay in responding. @Olical my comment stands: I'm happy to host all that data on a single cheapo $5/month DigitalOcean instance, which I'm sure is more than capable of handling the load. I just need the data.

**Comment by Olical** [comment]
Sounds good, I'll see about dumping everything that's there right now and getting it to you somehow, probably on Google drive although I'm not sure how big it'll be. I've been meaning to do this for a while, because I just don't have the time to maintain things other than my own very small blog.

There will be dataloss in between the dump and the pointing to the new server though, but it shouldn't be too bad.

**Comment by Olical** [comment]
It's also probably worth trying to get control of the domain from Coyote (I think?), I have DNS control through cloudflare, but that's all.

**Comment by Olical** [comment]
I have shared the entire archive with you on Google drive. Contains databases, source code and tooling, basically a dump of my server without my personal blog included. Let me know if you manage to get it all running and I can move the DNS over. Would be a good idea to get control of the domain though.

Steps I think you need to take:

 * Get a server.
 * Get a database.
 * Import full database SQL (I included split versions in case the single file is too big).
 * Configure DB connections in source code (host, user and password).
 * Upload all source and set up something to boot them (not sure about this part, host specific I guess?).
 * Change your local hosts file so you can point trillek.org to your new server on your machine and check it all.
 * If it's all good, send me the IP address and I'll repoint it :smile:
 * :rocket: :champagne: :tada: :100: :+1:

**Comment by adam4813** [comment]
I can contact coyote about updating the DNS, I believe, as I have spoken to
him before via email.

**Comment by Olical** [comment]
Sure thing, it isn't DNS as such though, it's the nameservers. You'll want
to point the nameservers to DigitalOcean, then you can manage the DNS
inside there. Right now the NS points to cloudflare where I have control of
DNS. I will be moving my personal domain so it uses DigitalOcean DNS too.
Sounds good though! Glad we're finally taking steps to get the data in your
hands, I've felt bad holding all of this for so long :) sorry to dump it on
you, but I think it's better in the long run. You can do whatever you want
with it now.

**Comment by milesrout** [comment]
I've contacted Coyote about the domain and he's said he'll get back to me soon.

**Comment by Olical** [comment]
My blog is all moved to linode and working well. I think there's less than a week before the forwarding to the new server stops working. So I'll need to sort out repointing of DNS to the new server or to your linode one. I assume everything is still working after the new server was created in webfaction?

**Comment by Olical** [comment]
The webfaction account will be shutting down in a few weeks, any progress on your own server?

**Comment by adam4813** [comment]
This has been resolved to a sufficient level

New domain is http://trillek.space/ with website and IRC logs hosted therein.

Forum and WIKI are not hosted, but WIKI can be accomplished via github.
